services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: invoice-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./app/backend/.env
    volumes:
      - ./app/backend:/app
      - /app/node_modules
    networks:
      - invoice-network
    
  # frontend:
  #   build:
  #     context: ./app/frontend
  #     dockerfile: Dockerfile
  #   container_name: invoice-frontend
  #   restart: always
  #   ports:
  #     - "4200:4200"
  #   env_file:
  #     - .env
  #   environment:
  #     API_URL: ${API_URL}
  #   volumes:
  #     - ./app/frontend:/app
  #     - /app/node_modules

networks:
  invoice-network:
    driver: bridge
    external: true
    name: shared-network